### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hrieke** [keyvanakbary/dni-nie-validator#2]
Hello,

I came across your code and was wondering under what license you wish to distribute your code under?
Yes, I did read:
https://keyvanakbary.com/comentar-codigo-una-mala-idea/
and it appears that you forgot to add this bit: Acceptable Comments: Legal comments... 😃 
Thank you!

**Comment by keyvanakbary** [comment]
[Just added MIT license](https://github.com/keyvanakbary/dni-nie-validator/blob/master/LICENSE), hope it helps! :)
